name: Deploy Zips to Firebase Hosting

on:
  push:
    branches:
      - anuj-asset-sync
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Run rebuild script
        run: bash scripts/extract_asset_zips.sh || true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Deploy to Firebase Hosting 1
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SYNC }}" | base64 --decode > serviceAccountKey.json
          export GOOGLE_APPLICATION_CREDENTIALS="$PWD/serviceAccountKey.json"

          npm install -g firebase-tools
          firebase deploy --only hosting:asset-sync-cuba

      # - name: Upload extracted files using update-single-file (TEST)
      #   run: |
      #     echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SYNC }}" | base64 --decode > serviceAccountKey.json
      #     export GOOGLE_APPLICATION_CREDENTIALS="$PWD/serviceAccountKey.json"

      #     npm install google-auth-library debug minimist

      #     # HARD SAFETY LIMIT
      #     MAX_FILES=100
      #     FILES=$(find public -type f | head -n $MAX_FILES)

      #     echo "Uploading files:"
      #     echo "$FILES"

      #     node scripts/update-single-file.cjs --project=asset-sync-cuba $FILES

      - name: Cleanup credentials
        if: always()
        run: rm -f serviceAccountKey.json
